# Advanced training transform with augmentations recommended in the report
_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.Resize
    size: [224, 224]
  - _target_: torchvision.transforms.RandomHorizontalFlip
    p: 0.5
  - _target_: torchvision.transforms.ColorJitter
    brightness: 0.2
    contrast: 0.3
    saturation: 0.2
    hue: 0.1
  - _target_: torchvision.transforms.RandomPerspective
    distortion_scale: 0.15
    p: 0.3
  - _target_: torchvision.transforms.RandomAffine
    degrees: 10
    translate: [0.1, 0.1]
    scale: [0.9, 1.1]
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]