_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.Resize
    size: [196, 196]
  - _target_: torchvision.transforms.RandomHorizontalFlip
  - _target_: torchvision.transforms.ToTensor
