# configs/dataset/train_transform/enhanced.yaml
_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.Resize
    size: [256, 256]  # Larger initial size for better crops
  - _target_: torchvision.transforms.RandomResizedCrop
    size: [224, 224]
    scale: [0.8, 1.0]  # Random scaling for robustness
    ratio: [0.75, 1.33]  # Aspect ratio variation
  - _target_: torchvision.transforms.RandomHorizontalFlip
    p: 0.5
  - _target_: torchvision.transforms.ColorJitter
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  - _target_: torchvision.transforms.RandomRotation
    degrees: 15
  - _target_: torchvision.transforms.RandomGrayscale
    p: 0.1
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  - _target_: torchvision.transforms.RandomErasing
    p: 0.1
    scale: [0.02, 0.33]
    ratio: [0.3, 3.3]