
instance:
  _target_: models.enhanced_combined_model.EnhancedCombinedModel
  image_mlp_layers: [1024, 1024, 1024]  # Not directly used but kept for compatibility
  text_model_name: 'facebook/bart-base'
  text_mlp_layers: [1024, 1024, 1024]  # Not directly used but kept for compatibility
  metadata_mlp_layers: [1024, 1024, 1024]  # Not directly used but kept for compatibility
  final_mlp_layers: [1024, 1024, 1024, 1024, 1]  # Final MLP layers
  num_channels: 1000  # Will be overridden with actual num_channels from dataset
  freeze_dinov2: True
  freeze_text_model: True
  metadata_percentage: 0.2  # Percentage of metadata to include
  attention_heads: 8  # Number of attention heads

name: EnhancedCombinedModel