instance:
  _target_: models.dinov2_bert_selfattn.DinoV2BertSelfAttention
  
  # Paramètres DinoV2
  dinov2_hidden_dims: [1024, 1024, 1024, 1024, 1024, 1024,]
  freeze_dinov2: True
  
  # Paramètres BERT
  bert_model: "bert-base-uncased"
  bert_hidden_dims: [1024, 1024, 1024, 1024, 1024, 1024,]
  freeze_bert: True
  text_max_length: 128
  
  # Paramètres auto-attention
  n_attention_heads: 8
  attention_dropout: 0.1
  
  # Paramètres MLP final
  final_hidden_dims: [1024, 1024, 1024, 1024, 1024, 1024,]
  final_dropout: 0.2

name: DINOV2_BERT_SELFATTN