instance:
  _target_: models.enhanced_combined_model.EnhancedCombinedModel
  image_mlp_layers: [1024, 512, 256]  # Not directly used but kept for compatibility
  text_model_name: 'facebook/bart-base'
  text_mlp_layers: [1024, 512, 256]  # Not directly used but kept for compatibility
  metadata_mlp_layers: [512, 256, 128]  # Not directly used but kept for compatibility
  final_mlp_layers: [1024, 512, 256, 128, 1]  # Final MLP layers
  num_channels: 1000  # Will be overridden with actual num_channels from dataset
  freeze_dinov2: True
  freeze_text_model: True
  metadata_percentage: 0.2  # Percentage of metadata to include
  attention_heads: 4  # Number of attention heads - using 4 for better divisibility

name: EnhancedCombinedModel