instance: 
  _target_: models.regressor.ImprovedMLPRegressor
  input_dim: 1152  
  # pour distil_bert et dino_vits avec concat: 768+384=1152
  # pour distil_bert et dino_vits avec fusion (donc projetes avant) : 256*3 = 768
  hidden_dim: [1024, 528, 256] 
  num_layers: 2
  dropout: 0.1

name: MLPRegressor