instance: 
  _target_: models.regressor.ImprovedMLPRegressor
  input_dim: 1024  # dépend de la concat de CLIP image (512) + texte (512)
  hidden_dim: 256
  num_layers: 2
  dropout: 0.4

name: MLPRegressor