instance:
  _target_: models.vit.ViTForRegression
  pretrained: True
  frozen_layers: 8
  hidden_dims: [1024, 512, 256]
  dropout_rate: 0.2
  use_text: True
  vit_model: "google/vit-base-patch16-224"

name: VIT